kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ./dockerfiles/Dockerfile
  context: .

spec:
  operator: vertexai
  image: image
  #command: "python3 -u main.py --operator=tf --echos=50 --tb-write=True"
  command: "python3 diagnostic_script.py --mode diagnostic"

  types:
    workerPoolSpecs:
    - machineSpec:
        machineType: n1-standard-4
      replicaCount: 1
