kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ./dockerfiles/gpu.Dockerfile
  context: .

spec:
  operator: vertexai
  image: image
  command: "python3 -u main.gpu.py --operator=tf  --sleep=20"
  #command: "python3 diagnostic_script.py --mode diagnostic"

  types:
    workerPoolSpecs:
    - machineSpec:
        machineType: n1-standard-4
        acceleratorType: NVIDIA_TESLA_T4
        acceleratorCount: 1
      replicaCount: 1
