kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: gpu.Dockerfile #gpu training
  #dockerfile: Dockerfile #non gpu training
  context: .

spec:
  operator: vertexai
  image: image
  #command: "python3 -u main.gpu.py --operator=tf  --sleep=20" #gpu training
  #command: "python3 -u /app/main.gpu.py --epochs=10 --lr=0.001" #new gpu training
  command: "echo 'Container works' && pwd && whoami"
  #command: "python3 -u main.py --operator=tf  --sleep=20" #non gpu training

  types:
    workerPoolSpecs:
    - machineSpec:
        machineType: n1-standard-4
        acceleratorType: NVIDIA_TESLA_T4 #gpu training
        acceleratorCount: 1 #gpu training
      replicaCount: 1
